#! /usr/bin/bash

clear
while [ 1 ]
do
    echo "PPPPPPPPPPPPPPPPPP"
    echo "P                 P "
    echo "P                  P"
    echo "P                   P "
    echo "P                  P"
    echo "P                 P "
    echo "PPPPPPPPPPPPPPPPPP"
    echo "P "
    echo "P"
    echo "P "
    echo "P"
    echo "P "
    echo "P "
    echo "P"
    echo "P "
    echo "P"
    echo " "
    sleep $1
    echo "IIIIIIIIIIIIIIIIII"
    echo "        I"
    echo "        I"
    echo "        I"
    echo "        I"
    echo "        I"
    echo "        I"
    echo "        I"
    echo "        I"
    echo "        I"
    echo "        I"
    echo "IIIIIIIIIIIIIIIIII"
    echo " "
    sleep $1
    echo "NN                N"
    echo "N N               N"
    echo "N  N              N"
    echo "N   N             N"
    echo "N    N            N"
    echo "N     N           N"
    echo "N      N          N"
    echo "N       N         N"
    echo "N        N        N"
    echo "N         N       N"
    echo "N          N      N"
    echo "N           N     N"
    echo "N            N    N"
    echo "N             N   N"
    echo "N              N  N"
    echo "N               N N"
    echo "N                NN"
    echo " "
    sleep $1    
    echo "K             K"
    echo "K            K"
    echo "K           K"
    echo "K          K"
    echo "K         K"
    echo "K        K"
    echo "K       K"
    echo "K      K"
    echo "K     K"
    echo "K    K"
    echo "K   K"
    echo "K  K"
    echo "K K"
    echo "KK"
    echo "K K"
    echo "K  K"
    echo "K   K"
    echo "K    K"
    echo "K     K"
    echo "K      K"
    echo "K       K"
    echo "K        K"
    echo "K         K"
    echo "K          K"
    echo "K           K"
    echo "K            K"
    echo "K             K"
    echo " "    
    sleep $1
    echo "U                 U"
    echo "U                 U"
    echo "U                 U"
    echo "U                 U"
    echo "U                 U"
    echo "U                 U"
    echo "U                 U"
    echo "U                 U"
    echo "U                 U"
    echo " U               U"
    echo "  U             U"
    echo "   U           U"
    echo "    UUUUUUUUUUU"
    sleep $1
    clear
done




